fonts:
  - path: assets/fonts/arial.ttf
    size: 32
backgrounds:
  - type: solid
    color: "#FFFFFF"
  - type: image
    image_path: "assets/backgrounds/default_background.png"
  - type: image
    image_path: "assets/backgrounds/default_background_2.png"
  - type: gradient
    start_color: [255, 0, 0]
    end_color: [0, 0, 255]
    direction: "horizontal"
  - type: noise

layout:
  type: simple
output:
  images_dir: outputs/images
  metadata_file: outputs/metadata.jsonl
dataset:
  source: csv
  path: data/input.csv
