fonts:
  - path: assets/fonts/arial.ttf
    size: 32
backgrounds:
  - type: noise
    noise_type: gaussian  
  - type: image
    image_path: 'assets/backgrounds/test_default_background_2.png'  

layout:
  type: simple
output:
  images_dir: outputs/images
  metadata_file: outputs/metadata.jsonl
dataset:
  source: csv
  path: data/input.csv
